SOURCE_FILE:= queue_destory.c queue_enter.c queue_init.c queue_out.c queue_print.c queue_test.c

OBJECT_FILE:= queue_destory.o queue_enter.o queue_init.o queue_out.o queue_print.o queue_test.o

compile:
	gcc -g -c $(SOURCE_FILE)

link:
	gcc $(OBJECT_FILE) -g -o ./a.out

clean:
	rm -rf ./*.o ./a.out
